### ISSUE TITLE
Implement Referee within St. Olaf CS

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/cs251-toolkit#7]
[Referee](https://github.com/StoDevX/referee) has been merged into this project. The code lives in [`/cs251tk/referee/`](https://github.com/StoDevX/cs251-toolkit/tree/master/cs251tk/referee) and [`/cs251k/cli/referee.py`](https://github.com/StoDevX/cs251-toolkit/blob/master/cs251tk/cli/referee.py).

I (@hawkrives) believes that it works, but it hasn't been tested fully.

Referee is built around processing GitLab webhooks, primarily the `push` event. When it receives an event, it downloads the code and runs it through the toolkit, in much the same manner as the manual toolkit, and sends the results as an email to the account that pushed.

I assume that we would want to run Referee on a CS server, rather than a lab machine.

The outstanding questions are:

- [x] How does Referee get webhooks?
    - RAB / someone writes a script to add the Referee endpoint to every student's repo
- [x] How does Referee run?
  - IDK. Currently, the code kinda assumes that it'd be run as a cgi script? So a new python process would be spawned for each request? It shouldn't be too hard to actually make a Python _server_, though, and that might be a better thing to do.

Actually, I think that's the only open question? Huh.

Plz comment with other questions so we can get some of this domain knowledge out of my head. Kthxbye.

> /cc @OmarShehata, @rye, @frantsen, @petersbob

**Comment by rye** [comment]
This issue was solved a while ago.  We are currently running Referee as a CGI script in a VM on _thing5_.  A cool part of this was that there wasn't any overhead with running a web server. (Besides the thing that spawns the CGI script after every webhook push.)

As such, I am marking this issue as closed, especially because [there are pending changes to be made to this model](https://github.com/StoDevX/referee/commit/2d398feff85ebc768fbe539d127f3dd810ea2e8e) (see: nascent dedicated web project)
