### ISSUE TITLE
[RFC] Ways to prevent student files from running arbitrary code

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/cs251-toolkit#8]
Currently, a student could submit a program that runs

```c++
#include <cstdio>
#include <cstdlib>

int main() {
  system("rm -rf ~/");
  return 0;
}
```

and `cs251tk` would happily run the code, removing everything in your home directory as it went.

Now, most Oles are not going to submit that; heck, most SD students probably don't know about `system()` at all. However, it's a vulnerability, and we should at least think about how to close it.

I've thought about using ["chroot jails"](http://unix.stackexchange.com/questions/105/chroot-jail-what-is-it-and-how-do-i-use-it) to cordon off the child processes, but those require you to run the parent as root.

This seems like a good fit for containers, but we would need to investigate how much disk space overhead they incur, unless the IT gods have deigned to increase the default H: drive above 500mb (or RAB's started including default `.gitignores` so we don't get media submissions), neither of which I think are likely to happen.

So: chroot, probably not; containers: need measuring.

**Comment by rye** [comment]
#9 mentions containerizing this, which is one—very worthy—approach to solving this problem.  Idk about how full the system will be in the Docker environment since I haven't picked a base image yet, but I think we can come up with some solutions to this.

Also consider:
 * **Timeouts**, which are already implemented, I think.
 * **SELinux doping**, to basically just run the process with the least permissions possible.
 * **`chown` and `chmod`ing** the clone so that it is owned by the user's account but executable by everyone.

**Comment by hawkrives** [comment]
- [x] Timeouts are indeed implemented, and default to 4 seconds per executable.
- [ ] SELinux would be nice, but isn't feasible until we have Docker/etc so that it only runs on Linux, I don't think

**Comment by rye** [comment]
I think many Docker images would also not have SELinux so it's questionable.  Probably not necessary, either, since I think using timeouts, Linux permissions, and then watching usages is fine.

**Comment by hawkrives** [comment]
So, just to clarify: for the student's local repo clone, if we chmod it to their user / not our user, but leave the binaries as executable by anyone, the binaries shouldn't be able to remove / edit / read files in our home folders?

Because if so, wow. That's nice.

**Comment by rye** [comment]
I believe this is correct—it's been a while since I've dealt with permissions, but to my knowledge, if you chmod a file to a user and you give that user permissions to their clone, (recursively, via `chown -R`) and then—most importantly—you run the program *as that user*, since that username doesn't have access to your files, they can't do anything naughty.

**Comment by rye** [comment]
Yeah, I think we solved this one, too.  We probably don't need to keep this issue around either, however it will be good to reference some of these ideas when we move forward with the nascent Referee project.
